### ISSUE TITLE
RuntimeError: Cannot load plugin "nonebot_plugin_imageutils"!

### ISSUE THREAD

**Issue by jx9468** [noneplugin/nonebot-plugin-memes#10]
![aa](https://user-images.githubusercontent.com/78193384/174478564-9bdad06b-4247-4827-826d-ab0854ff9221.png)
![bb](https://user-images.githubusercontent.com/78193384/174478565-66cc92af-2bb8-45bd-a54e-69b7b2453896.png)
已经用pip install nonebot_plugin_imageutils 安装了依赖但是还是会报RuntimeError: Cannot load plugin "nonebot_plugin_imageutils"!是什么原因😭
腾讯轻量windows系统

**Comment by MeetWq** [comment]
上面还有报错吗？截全点看看

**Comment by jx9468** [comment]
> 上面还有报错吗？截全点看看

[ERROR] nonebot | Failed to import "nonebot_plugin_imageutils"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 22, in <module>
    nonebot.load_plugins("src/plugins")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\src\plugins\nonebot_plugin_petpet\__init__.py", line 10, in <module>
    require("nonebot_plugin_imageutils")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 163, in require
    plugin = load_plugin(name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_imageutils\__init__.py", line 1, in <module>
    from .build_image import BuildImage
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_imageutils\build_image.py", line 1, in <module>
    import cv2 as cv
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
06-19 20:03:08 [ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 22, in <module>
    nonebot.load_plugins("src/plugins")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\src\plugins\nonebot_plugin_petpet\__init__.py", line 10, in <module>
    require("nonebot_plugin_imageutils")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 165, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_imageutils"!

**Comment by MeetWq** [comment]
你 `pip install nonebot_plugin_imageutils` 的时候有没有报错？

**Comment by yellowiop123** [comment]
我也遇到这个情况了

**Comment by yellowiop123** [comment]
![image](https://user-images.githubusercontent.com/44320586/174576378-5ca75460-9b24-4f1c-b066-1b25ecd6293e.png)
系统是Ubuntu20.04

**Comment by yellowiop123** [comment]
我也遇到这个情况了
系统是Ubuntu20.04

**Comment by MeetWq** [comment]
检查一下装的和运行的是不是一个环境

**Comment by yellowiop123** [comment]
> 检查一下装的和运行的是不是一个环境

还真是 忘记在虚拟环境里安装了 在虚拟环境里面重新安装了一遍就可以了 谢谢大佬

**Comment by jx9468** [comment]
我装了一遍真寻版本的petpet这边就也好了，也不清楚是不是我前面依赖安装出问题了，重装了几遍依赖都不行😂
