### ISSUE TITLE
【报错】cv2找不到指定模块

### ISSUE THREAD

**Issue by nicklly** [noneplugin/nonebot-plugin-memes#102]
MQ佬救命.jpg

`[ERROR] nonebot | Failed to import "nonebot_plugin_memes"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LittlePaimon-Bot\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python311\Lib\site-packages\nonebot_plugin_memes\__init__.py", line 8, in <module>
    from meme_generator.exception import (
  File "C:\Program Files\Python311\Lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Program Files\Python311\Lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Program Files\Python311\Lib\site-packages\meme_generator\meme.py", line 22, in <module>
    from pil_utils import BuildImage
  File "C:\Program Files\Python311\Lib\site-packages\pil_utils\__init__.py", line 1, in <module>
    from .build_image import BuildImage
  File "C:\Program Files\Python311\Lib\site-packages\pil_utils\build_image.py", line 5, in <module>
    import cv2
  File "C:\Program Files\Python311\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Program Files\Python311\Lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: 找不到指定的模块。`

服务器系统是 windows server 2012R2
opencv-python 也安装了 版本号4.10.0.84

**Comment by yuanbolin** [comment]
楼上问题和出现版本我这里也一一模一样

**Comment by MeetWq** [comment]
需要安装 c++ 运行库，看opencv-python的说明：https://github.com/opencv/opencv-python#frequently-asked-questions
