### ISSUE TITLE
【报错】[ERROR] uvicorn | Application startup failed. Exiting.

### ISSUE THREAD

**Issue by freght** [noneplugin/nonebot-plugin-memes#109]
08-19 05:43:13 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\Python3.12\Lib\site-packages\starlette\routing.py", line 730, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\Python3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3.12\Lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\Python3.12\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\Python3.12\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\Python3.12\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 75, in init_orm
    _init_orm()
  File "D:\Python3.12\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 102, in _init_orm
    _init_engines()
  File "D:\Python3.12\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 172, in _init_engines
    _engines[""] = _create_engine(plugin_config.sqlalchemy_database_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3.12\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 159, in _create_engine
    return create_async_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3.12\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 121, in create_async_engine
    return AsyncEngine(sync_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python3.12\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 1031, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'psycopg2' is not async.

08-19 05:43:13 [ERROR] uvicorn | Application startup failed. Exiting.

我只能把nonebot-plugin-orm和sqlalchemy alembic卸载掉，请问大佬有什么解决办法啊

**Comment by MeetWq** [comment]
你应该是改过 `sqlalchemy_database_url` 配置

具体去看 [nonebot-plugin-orm](https://github.com/nonebot/plugin-orm) 说明

**Comment by freght** [comment]
> 你应该是改过 `sqlalchemy_database_url` 配置
> 
> 具体去看 [nonebot-plugin-orm](https://github.com/nonebot/plugin-orm) 说明

可是我重新创建了nb框架安装memes还是提示这个

**Comment by MeetWq** [comment]
你应该去 orm 插件问，和本插件关系不大

**Comment by freght** [comment]
> 你应该去 orm 插件问，和本插件关系不大

哦哦，好的
