### ISSUE TITLE
加载时报错

### ISSUE THREAD

**Issue by zfztty** [noneplugin/nonebot-plugin-memes#116]
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot_plugin_memes\__init__.py", line 11, in <module>
    from . import matchers, migrations  # noqa
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot_plugin_memes\matchers\__init__.py", line 1, in <module>
    from . import info, manage, search, help, command, statistics  # noqa
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot_plugin_memes\matchers\info.py", line 6, in <module>
    from .utils import find_meme
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\nonebot_plugin_memes\matchers\utils.py", line 3, in <module>
    from meme_generator import Meme
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\meme_generator\manager.py", line 11, in <module>
    from .meme import CommandShortcut, Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\meme_generator\meme.py", line 9, in <module>
    from pil_utils import BuildImage
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\pil_utils\__init__.py", line 1, in <module>
    from .build_image import BuildImage as BuildImage
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\pil_utils\build_image.py", line 15, in <module>
    from .text2image import Text2Image
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\pil_utils\text2image.py", line 12, in <module>
    from .fonts import Font, get_proper_font
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\pil_utils\fonts.py", line 6, in <module>
    from matplotlib.font_manager import FontProperties, fontManager
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\matplotlib\__init__.py", line 263, in <module>
    _check_versions()
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\matplotlib\__init__.py", line 257, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\download\yunzai2\nb2\nb2\.venv\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

**Comment by MeetWq** [comment]
试试 `pip install msvc-runtime`

**Comment by zfztty** [comment]
> 试试 `pip install msvc-runtime`

解决了谢谢佬
