### ISSUE TITLE
某些带图片的表格, 自己加图片可以, at人的时候报 timeout

### ISSUE THREAD

**Issue by syvshc** [noneplugin/nonebot-plugin-memes#117]
发送“原神启动 自己”会报错
![image](https://github.com/user-attachments/assets/1ba8ffd8-c8d3-4316-89ec-f1d343e2a8ad)

```
发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 0,
    "errMsg": ""
}

    at Timeout.sendDataCallback [as _onTimeout] (file:///D:/git/bot/NapCat.Shell/napcat.mjs:7659:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
发送“原神启动 <图片>” 貌似是没问题的
![image](https://github.com/user-attachments/assets/aa8e9861-c904-454a-a812-f8603fb38116)

**Comment by syvshc** [comment]
并且抓头像功能应该是正常的
![image](https://github.com/user-attachments/assets/36daa07e-3230-43db-8efd-bb41207490bd)

**Comment by syvshc** [comment]
看了一下 napcat 那边也有报错 
```
09-28 11:20:48 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "D:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "D:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "D:\ProgramData\miniconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "D:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "D:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "D:\ProgramData\miniconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\command.py", line 258, in _
    await process(matcher, session, meme, image_sources, texts, user_infos, args)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\command.py", line 82, in process
    await msg.send()
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\message.py", line 1395, in send
    res = await fn.send_to(target, bot, msg, **kwargs)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\adapters\onebot11\exporter.py", line 154, in send_to
    return await bot.send(target, message, **kwargs)  # type: ignore
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 237, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 190, in send
    return await bot.send_msg(**params)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\syvshc-lily\qqbot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": ""\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///D:/git/bot/NapCat.Shell/napcat.mjs:7659:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 0,\n    "errMsg": ""\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///D:/git/bot/NapCat.Shell/napcat.mjs:7659:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo='99')
```

**Comment by MeetWq** [comment]
看着像是 napcat 发送超时，你多试几次呢？

**Comment by syvshc** [comment]
> 看着像是 napcat 发送超时，你多试几次呢？

目前 艾特人的时候还没有成功的，但是自己添加图片没有失败的（

**Comment by MeetWq** [comment]
别的表情呢？有可能这个图片太大了

**Comment by syvshc** [comment]
> 别的表情呢？有可能这个图片太大了

简单测试了几个, 抓头像的功能应该是没问题的

**Comment by MeetWq** [comment]
所以到底是什么问题？麻烦描述清楚。
只有“原神启动 自己”会报错？别的表情使用“自己”或“@”有问题吗？
我也是用的napcat，是没问题的。
我怀疑只是某些图片被夹了，你可以手动下载自己的头像然后“原神启动”试试。
总之这个报错和插件没关系。
