### ISSUE TITLE
表情包指令+图片的方式制作表情包报错

### ISSUE THREAD

**Issue by miao19991020** [noneplugin/nonebot-plugin-memes#121]
当用指令+图片的方式制作表情包时无法从对应域名处请求到图片
```
url:https://c2cpicdw.qpic.cn&rkey=CAESOBkcro_MGujoYT9v5fddQeldlAZ7qNFTz4TUaqjGwnembYdBqYrBm8zyDNg7s31lsw24AKYEZc0H&spec=0&rf=naio
GET
https://c2cpicdw.qpic.cn&rkey=caesobkcro_mgujoyt9v5fddqeldlaz7qnftz4tuaqjgwnembydbqyrbm8zydng7s31lsw24akyezc0h&spec=0&rf=naio
11-16 17:03:03 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164) running complete
11-16 17:03:03 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164) failed.
Traceback (most recent call last):
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpx\_transports\default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "D:\Python\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "D:\pyProject\robot\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed
```

**Comment by MeetWq** [comment]
你的域名有问题，是你用的协议端的问题

**Comment by miao19991020** [comment]
> 你的域名有问题，是你用的协议端的问题

懂了，谢谢
