### ISSUE TITLE
加载时报错

### ISSUE THREAD

**Issue by ddyyluolan** [noneplugin/nonebot-plugin-memes#127]
11-26 13:13:07 [ERROR] nonebot | Failed to import "nonebot_plugin_memes"
Traceback (most recent call last):
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 133, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 67, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 205, in load_all_plugins
    return set(
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot_plugin_memes\__init__.py", line 11, in <module>
    from . import matchers, migrations  # noqa
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\__init__.py", line 1, in <module>
    from . import info, manage, search, help, command, statistics  # noqa
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\info.py", line 6, in <module>
    from .utils import find_meme
  File "D:\qqcat\bot2\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\utils.py", line 3, in <module>
    from meme_generator import Meme
  File "D:\qqcat\bot2\.venv\Lib\site-packages\meme_generator\__init__.py", line 3, in <module>
    from meme_generator.config import meme_config as config
  File "D:\qqcat\bot2\.venv\Lib\site-packages\meme_generator\config.py", line 70, in <module>
    meme_config = Config.load()
  File "D:\qqcat\bot2\.venv\Lib\site-packages\meme_generator\config.py", line 59, in load
    return type_validate_python(cls, toml.load(config_file_path))
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "D:\qqcat\bot2\.venv\Lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 3 column 1 char 46)
11-26 13:13:07 [SUCCESS] nonebot | Running NoneBot...
11-26 13:13:07 [INFO] uvicorn | Started server process [22876]
11-26 13:13:07 [INFO] uvicorn | Waiting for application startup.
11-26 13:13:07 [INFO] nonebot_plugin_orm | 没有检测到新的升级操作
11-26 13:13:07 [INFO] uvicorn | Application startup complete.
11-26 13:13:07 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:5140 (Press CTRL+C to quit)
11-26 13:13:09 [INFO] uvicorn | ('127.0.0.1', 63812) - "WebSocket /onebot/v11/ws" [accepted]

**Comment by ddyyluolan** [comment]
已解决，问题在于配置文件的浮点数问题
