### ISSUE TITLE
带图制作表情包出错,TypeError: AsyncClient.init() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by ternurarl** [noneplugin/nonebot-plugin-memes#132]
napcat版本v4.2.36。onebot v11
插件安装了最新的版本
只用文字生成表情包没问题

尝试关闭了代理，报一样的错

Alconna::小画家 对 "小画家 [image]" 的解析结果是 (matched=True, header_match=(origin='小画家' result='小画家' matched=True groups={}), main_args={'meme_params': (Image(id='000001564e61704361744f6e65426f747c4d736746696c657c317c755f417059674673457156484b6b57577a6d3451594b55777c373434393234303238383938373136303536387c373434393234303238383938373136303536397c4568536b45385945726765425032615241787a774b4a5532494748456e4269322d6751675f676f6f754b337367494b7569674d79424842796232526145446e676e58387a57536f5f2d50446548333835336773.787F3F327D1FDD41A6B86741FD81CD8C.jpg', url='https://multimedia.nt.qq.com.cn/download?appid=1406&fileid=EhSkE8YErgeBP2aRAxzwKJU2IGHEnBi2-gQg_goouK3sgIKuigMyBHByb2RaEDngnX8zWSo_-PDeH3853gs&rkey=CAMSKMa3OFokB_Tl9KsOf201njvpgb263NtZZrCoyvDFpa32v6di1hoD8l0', path=None, raw=None, mimetype=None, name='image.png'),)})
12-17 14:05:26 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164)
12-17 14:05:26 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164)
12-17 14:05:26 [DEBUG] nonebot | Running handler Dependent(call=_)
12-17 14:05:26 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164) running complete

**12-17 14:05:26 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=164) failed.
Traceback (most recent call last):**

  File "<string>", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 678, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2033, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\command.py", line 265, in _
    await process(matcher, session, meme, image_sources, texts, user_infos, args)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\command.py", line 56, in process
    images.append(await image_source.get_image())
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot_plugin_memes\matchers\command.py", line 100, in get_image
    result = await image_fetch(self.event, self.bot, self.state, self.img)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot_plugin_alconna\uniseg\tools.py", line 48, in image_fetch
    resp = await bot.adapter.request(req)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\internal\adapter\adapter.py", line 92, in request
    return await self.driver.request(setup)
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\drivers\httpx.py", line 129, in request
    async with self.get_session(
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\internal\driver\abstract.py", line 269, in __aenter__
    await self.setup()
  File "C:\Users\Administrator\di\.venv\Lib\site-packages\nonebot\drivers\httpx.py", line 100, in setup
    self._client = httpx.AsyncClient(
**TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'**
12-17 14:05:26 [DEBUG] nonebot | Stop event propagation
12-17 14:05:26 [DEBUG] nonebot | Checking for matchers completed

**Comment by MeetWq** [comment]
降级 httpx 到 0.27.2
