### ISSUE TITLE
安装以后启动失败报错

### ISSUE THREAD

**Issue by qqq114168** [noneplugin/nonebot-plugin-memes#135]
[ERROR] uvicorn | Traceback (most recent call last):
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "D:\Program Files\Python311\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 75, in init_orm
    _init_orm()
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 102, in _init_orm
    _init_engines()
  File "D:\Program Files\Qbot\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 182, in _init_engines
    raise ValueError(
ValueError: 必须指定一个默认数据库 (SQLALCHEMY_DATABASE_URL 或 SQLALCHEMY_BINDS[""]). 可以通过 `pip install nonebot-plugin-orm[default]` 获得开箱即用的数据库配置.

12-23 19:13:07 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by qqq114168** [comment]
![image](https://github.com/user-attachments/assets/0f03300d-8e2d-47e7-a9b2-b00877eecdbd)
执行完提示命令还是报错
麻烦大大看看

**Comment by MeetWq** [comment]
在虚拟环境下执行pip

**Comment by qqq114168** [comment]
大大 没听懂什么意思

**Comment by qqq114168** [comment]
![image](https://github.com/user-attachments/assets/f3096664-3267-4022-922c-ecb379ae4165)
执行了

**Comment by qqq114168** [comment]
这个有影响不
