### ISSUE TITLE
插件运行报错

### ISSUE THREAD

**Issue by wu5288540** [noneplugin/nonebot-plugin-memes#24]
[ERROR] nonebot | Failed to import "nonebot_plugin_memes"
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.10/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/nbot/./bot.py", line 58, in <module>
    nonebot.load_plugin("nonebot_plugin_memes")
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/nonebot_plugin_memes/__init__.py", line 12, in <module>
    from nonebot.plugin import PluginMetadata
ImportError: cannot import name 'PluginMetadata' from 'nonebot.plugin' (/usr/local/lib/python3.10/site-packages/nonebot/plugin/__init__.py)

尝试重装本插件，结果是……除了本插件以外的其他插件全部寄了，export没了，得重新装apscheduler和插件

脑仁疼
nbot版本是rc-1

**Comment by MeetWq** [comment]
那是别的插件的问题😂
可以暂时把nb降级到beta5版本，因为有些插件还没适配
