### ISSUE TITLE
使用@报错

### ISSUE THREAD

**Issue by INSide-734** [noneplugin/nonebot-plugin-memes#45]
````
```
04-06 01:23:39 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.memes) failed.
Traceback (most recent call last):
  File "/root/zhenxun_bot/bot.py", line 23, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 104, in __call__
    values = await self.solve(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 216, in solve
    await param._solve(**params)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.10/lib/python3.10/site-packages/nonebot/internal/params.py", line 158, in _solve
    return await task
  File "/root/zhenxun_bot/extensive_plugin/memes/depends.py", line 93, in dependency
    image_sources.append(user_avatar(bot, str(msg_seg.data["qq"])))
TypeError: user_avatar() missing 1 required positional argument: 'user_id'
```
````

**Comment by MeetWq** [comment]
更新

**Comment by INSide-734** [comment]
原因是不适配nonebot 2.0.0rc4

**Comment by MeetWq** [comment]
>

**Comment by INSide-734** [comment]
并没有，我是直接clone到目录下运行

**Comment by MeetWq** [comment]
???
那你看看 93 行有没有这句话
```
  File "/root/zhenxun_bot/extensive_plugin/memes/depends.py", line 93, in dependency
    image_sources.append(user_avatar(bot, str(msg_seg.data["qq"])))
```

**Comment by INSide-734** [comment]
没有![IMG_20230406_120936.jpg](https://user-images.githubusercontent.com/109641391/230270030-0a18205c-fe89-4624-8a65-d9de6da6bb8b.jpg)
