### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by Ble55me** [noneplugin/nonebot-plugin-memes#46]
`04-06 23:08:46 [INFO] nonebot_plugin_memes | 正在检查资源文件...
04-06 23:08:46 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlite3.IntegrityError: UNIQUE constraint failed: metainfo.key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\nonebot_plugin_sqlalchemy\__init__.py", line 49, in on_startup
    await _fire(self._on_engine_created_callback)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\nonebot_plugin_sqlalchemy\__init__.py", line 25, in _fire
    await gather(*coros)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\nonebot_plugin_mahjong_scoreboard\model\orm\_data_source\metainfo.py", line 47, in initialize_metainfo
    await session.commit()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 810, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 1218, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 4155, in flush
    self._flush(objects)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 4291, in _flush
    with util.safe_reraise():
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\session.py", line 4252, in _flush
    flush_context.execute()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 467, in execute
    rec.execute(self)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\orm\persistence.py", line 1020, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\sql\elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 254, in _handle_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\core.py", line 137, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\liteyuki-Yp9xpnas-py3.10\lib\site-packages\aiosqlite\core.py", line 110, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: metainfo.key
[SQL: INSERT INTO metainfo ("key", value) VALUES (?, ?)]
[parameters: ('db_version', '2')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

04-06 23:08:46 [ERROR] uvicorn | Application startup failed. Exiting.`

**Comment by MeetWq** [comment]
不是本插件的问题，这个插件没有用到数据库
