### ISSUE TITLE
无法下载资源

### ISSUE THREAD

**Issue by he0119** [noneplugin/nonebot-plugin-memes#5]
看起来是 `jsdelivr` 炸了。

```log
05-18 16:58:53 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_memes, type=message, priority=13, temp=False>
05-18 16:59:13 [WARNING] nonebot_plugin_memes | Error downloading https://cdn.jsdelivr.net/gh/MeetWq/nonebot-plugin-memes@main/resources/fonts/NotoColorEmoji.ttf, retry 0/3:
05-18 16:59:33 [WARNING] nonebot_plugin_memes | Error downloading https://cdn.jsdelivr.net/gh/MeetWq/nonebot-plugin-memes@main/resources/fonts/NotoColorEmoji.ttf, retry 1/3:
05-18 16:59:53 [WARNING] nonebot_plugin_memes | Error downloading https://cdn.jsdelivr.net/gh/MeetWq/nonebot-plugin-memes@main/resources/fonts/NotoColorEmoji.ttf, retry 2/3:
05-18 16:59:53 [WARNING] nonebot_plugin_memes | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/__init__.py", line 56, in handle
    res = await meme.func(texts)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/normal_meme.py", line 128, in make_diyu
    await draw_text(frame, (x, y), text, font=font, fill="#000000")
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/functions.py", line 115, in draw_text
    emoji_font_file = BytesIO(await get_font(EMOJI_FONT))
  File "/usr/local/lib/python3.9/site-packages/aiocache/decorators.py", line 93, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiocache/decorators.py", line 108, in decorator
    result = await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/download.py", line 52, in get_font
    return await get_resource("fonts", name)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/download.py", line 36, in get_resource
    data = await download(url)
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_memes/download.py", line 24, in download
    raise DownloadError
nonebot_plugin_memes.download.DownloadError

05-18 16:59:53 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_memes, type=message, priority=13, temp=False> running complete
```

**Comment by EE0CFF** [comment]
> 有什么推荐的 github 代理站吗（

同下载失败，请问应该自行把资源放到哪个文件夹呢，系统是debian11

**Comment by MeetWq** [comment]
放到机器人运行目录下的 `data/memes` 文件夹下

下载问题我有空再修
