### ISSUE TITLE
加载时报错，显示插件已存在，用的是真寻bot

### ISSUE THREAD

**Issue by eniod** [noneplugin/nonebot-plugin-memes#52]
错误代码
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_plugins("nonebot_plugin_memes")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-_aGgcQvQ-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 43, in load_plugins
    manager = PluginManager(search_path=plugin_dir)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-_aGgcQvQ-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 52, in __init__
    self.prepare_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-_aGgcQvQ-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 112, in prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: config! Check your plugin name

**Comment by MeetWq** [comment]
你的插件是怎样安装的？

**Comment by eniod** [comment]
> 你的插件是怎样安装的？

pip后剪切粘贴过去的

**Comment by eniod** [comment]
> 你的插件是怎样安装的？

pip后剪切粘贴到bot的根目录，然后在bot.py里面加入nonebot.load_plugins("nonebot_plugin_memes")

**Comment by MeetWq** [comment]
load_plugins 是加载路径下所有的插件，应该用 load_plugin

或者放到真寻的插件文件夹里

**Comment by MeetWq** [comment]
你 meme-generator 没装啊，检查一下是不是环境错了

**Comment by eniod** [comment]
> 你 meme-generator 没装啊，检查一下是不是环境错了

meme-generator装了，难道要在虚拟环境里也装一次吗

**Comment by jcjrobert** [comment]
> > 你 meme-generator 没装啊，检查一下是不是环境错了
> 
> meme-generator装了，难道要在虚拟环境里也装一次吗

不在同个虚拟环境里，插件要怎么检测到这个模块...
你应该使用api版本，这样分开就没什么问题

**Comment by eniod** [comment]
> > > 你 meme-generator 没装啊，检查一下是不是环境错了
> > 
> > 
> > meme-generator装了，难道要在虚拟环境里也装一次吗
> 
> 不在同个虚拟环境里，插件要怎么检测到这个模块... 你应该使用api版本，这样分开就没什么问题

好的，谢谢，解决了
