### ISSUE TITLE
使用膜拜表情包的时候的报错

### ISSUE THREAD

**Issue by hakureireimusama** [noneplugin/nonebot-plugin-memes#83]
使用膜拜表情包的时候的报错，这是什么原因导致的？
我用的是OpenShamrock登录的qq，像是“玩”，“喜报”这些表情包都没有问题可以生成

03-02 23:08:06 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_memes, lineno=349)
03-02 23:08:06 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_memes, lineno=349) running complete
03-02 23:08:06 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_memes, lineno=349) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot_plugin_memes\__init__.py", line 339, in handle
    await process(matcher, meme, image_sources, texts, user_infos, args)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot_plugin_memes\__init__.py", line 248, in process
    images.append(await image_source.get_image())
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot_plugin_memes\depends.py", line 30, in get_image
    result = await image_fetch(self.event, self.bot, self.state, self.img)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot_plugin_alconna\uniseg\tools.py", line 32, in image_fetch
    resp = await bot.adapter.request(req)
  File "C:\bot\Haruka-Bot\.venv\lib\site-packages\nonebot\internal\adapter\adapter.py", line 90, in request
    raise TypeError("Current driver does not support http client")
TypeError: Current driver does not support http client

**Comment by hakureireimusama** [comment]
![QQ截图20240302231559](https://github.com/noneplugin/nonebot-plugin-memes/assets/49976244/161b115a-c45f-435e-91c6-64f14f0a6fbb)
我发现像是这样 命令+图片 的形式会报错，直接@用户就不会报错

**Comment by MeetWq** [comment]
看置顶issue
