### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 26: invalid start byte 加载插件出错 该如何解决

### ISSUE THREAD

**Issue by Vjjvj** [noneplugin/nonebot-plugin-memes#98]
06-05 11:56:01 [ERROR] nonebot | Failed to import "nonebot_plugin_memes"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\nonebot_plugin_memes\__init__.py", line 8, in <module>
    from meme_generator.exception import (
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\meme_generator\__init__.py", line 3, in <module>
    from meme_generator.config import meme_config as config
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\meme_generator\config.py", line 72, in <module>
    meme_config = Config.load()
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\meme_generator\config.py", line 61, in load
    return cls.parse_obj(toml.load(config_file_path))
  File "C:\Users\Administrator\nb2\.venv\Lib\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 26: invalid start byte

**Comment by MeetWq** [comment]
可以把配置文件删掉再试，具体位置在 `C:\Users\<username>\AppData\Roaming\nonebot2\nonebot_plugin_memes` 下面
